### ISSUE TITLE
After closing the channel, the token is returned to the account address, but this transaction is not displayed in "Account Activities".

### ISSUE THREAD

**Issue by neocarmack** [omnilaboratory/OBAndroid#76]

**Comment by wxf4150** [comment]
close  asset-channel may have this issue. 

now we use  cooperativeClose for asset-channel :
* testnet/regtest: 
who invoke cooperativeClose in app, app will receive an closeTxid, app can use this closeTxid get the asset-transaction record,and filter the outputs  the  from closeTx by  wallet default address ,the filtered output  can display in "Account Activities" ; and the channel's  otherside app will not receive the  closeTxid.

* mainnet:
because mainet  not support send2many, it will not  support cooperativeClose.  
we add a new  method Ob_SafeBox_CloseChannel derive from cooperativeClose with the same api , and return one closeTx; Ob_SafeBox_CloseChannel use  simpleSend,   
Ob_SafeBox_CloseChannel will gen "two closeTx", and return the first  closeTx's hash,  and the first closeTx "may  not inlcude" output for the  invoker's wallet default address.


other close method  which need sweep, example rsmc/htlc/closeAddress  derived from wallte temporary ; 
these first level  closeTx  will not contain output for the wallet default address . 
second level sweepTx may contain output for user wallte default address.

**Comment by wxf4150** [comment]
for consistency with mainnet, two days ago ,we update  testnet/regtest all use Ob_SafeBox_CloseChannel which use simpleSend.

**Comment by wxf4150** [comment]
>  Ob_SafeBox_CloseChannel will gen "two closeTx", and return the first closeTx's hash, and the first closeTx "may not inlcude" output for the invoker's wallet default address.

i have update  Ob_SafeBox_CloseChannel  behavior at commit  omnilaboratory/lnd@3febdfe
